### ISSUE TITLE
Add a schema for compact tours

### ISSUE THREAD

**Issue by bartfeenstra** [iziteq/izi-api-schemes#3]
There is no schema for compact tours and tourist attractions. Could you add them? Please refer to Andrei Arkhipov to verify the priority of this request.

**Comment by vitaly-dukhov** [comment]
We use common schema for all CompactMTGObjects (compactmtgobjects/common_compact_object)

Do you need a scheme for tour or for all compact objects(museum, exhibit, collection etc)?

**Comment by bartfeenstra** [comment]
I used the common schema, but for forwards-compatibility having a specific schema per object type is best, so you can easily add properties without anyone having to use a different schema. Until there are new properties, the tour and tourist attraction schemas can just be a references to the common schema.

**Comment by vitaly-dukhov** [comment]
OK. I will add all schemes on Monday.

**Comment by bartfeenstra** [comment]
Example: In version 1.0.0 there are no special properties for tours and tourist attractions, so their schemas are just references to the common schema. In version 1.1.0 you can extend these schemas with optional properties, but our application (the new website) will not have to be changed at all, because it uses the tour and tourist attraction schemas already. We just pull in the updates through Composer and we're done.

**Comment by vitaly-dukhov** [comment]
On Tuesday. On Monday we have Day off International Women's Day

**Comment by vitaly-dukhov** [comment]
Could you add base variant of tour compact schema (with reference to common schema....) Later I will actualize it (fill with the correct set of properties) .

**Comment by vitaly-dukhov** [comment]
I've added compact tour schema. PLs check check that it's what you need

**Comment by bartfeenstra** [comment]
Thanks, they work well. Could you add some more for compact tourist attractions, compact exhibits, compact museums, compact story navigations, and compact collections? Then there will be a schema for every object type.

**Comment by vitaly-dukhov** [comment]
Have done
