### ISSUE TITLE
Performance: reference local schemas only

### ISSUE THREAD

**Issue by bartfeenstra** [iziteq/izi-api-schemes#5]
We validate messages a lot and every time multiple schemas are retrieved from Github. This causes a single validation to take between 500ms and 1000ms. All required schema files seem to come from the same repository anyway, so can't the schemas reference other local schema files?

**Comment by bartfeenstra** [comment]
I'm trying to work on a fix. It seems our JSON validator (https://github.com/justinrainbow/json-schema) contains a bug, though, so it will take a while.

**Comment by bartfeenstra** [comment]
The PR is located at https://github.com/iziteq/izi-api-schemes/pull/6

**Comment by vitaly-dukhov** [comment]
Can I close this issue?

**Comment by bartfeenstra** [comment]
Yes.
